#!/bin/sh
# Runs an opengl or vulkan app on the nvidia dgpu. It is not needed for cuda,
# those programs open the nvidia device on their own.

export __NV_PRIME_RENDER_OFFLOAD=1
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only
export VK_DRIVER_FILES=/usr/share/vulkan/icd.d/nvidia_icd.json
export LIBVA_DRIVER_NAME=nvidia

exec "$@"
